name: moduleinfo

on: [workflow_dispatch]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
       - name: Check out repository code
         uses: actions/checkout@v4
       - name: Export module info
         shell: pwsh
         run: |
           Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
           Install-Module UncommonSense.Hap -Scope CurrentUser
           $env:PSModulePath += ':/home/runner/work/UncommonSense.Asn'
           Import-Module UncommonSense.Asn.psd1 -Force
           Get-Command -Module UncommonSense.Asn | Get-Help | Select-Object ModuleName, Name, Synopsis | ConvertTo-Json | Set-Content -Path summary.json
       - name: Commit and push feed
         shell: bash
         run: |
           git config user.name github-actions
           git config user.email github-actions@github.com
           git pull
           git add .
           git commit -m "generated" || echo "No changes to commit"
           git push